# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

trigger:
  branches:
    include:
      - 'master'
      - 'release/*'

pr:
- '*'

variables:
- name: BuildNumber
  value: $[counter('buildnumber')]

jobs:
- job: Build
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-latest
      Windows:
        vmImage: windows-2019
  pool:
    vmImage: $(vmImage)
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1
    inputs:
      version: '3.1.x'
  - task: UseDotNet@2
    displayName: Install .NET Core 2.1
    inputs:
      version: '2.1.x'
  - powershell: ./build.ps1 -ci
    displayName: Invoke build.ps1
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: $(vmImage)
      testRunner: vstest
      testResultsFiles: '**/*.trx'
  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage results
    continueOnError: true
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: coverlet/reports/Cobertura.xml
  - publish: 'artifacts/'
    artifact: 'Packages'
    displayName: Publish artifacts
    condition: and(succeeded(), eq('windows-2019', variables['vmImage']))
